server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #GitHub上面的git仓库名字
          uri: https://github.com/SongSongSun/springcloud-config.git
          skipSslValidation: true
          ####搜索目录
          search-paths:
            - springcloud-config
          force-pull: true
          username: SongSongSun
          password: zaijian9980
      ####读取分支
      label: main
  rabbitmq:
    host: 192.169.1.52
    port: 5672
    username: admin
    password: 123456


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://192.169.1.135:7001/eureka,http://192.168.1.135:7002/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

