server:
  port: 7002

eureka:
  instance:
    hostname: 192.168.1.135 #ureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://192.169.1.135:7001/eureka/
  server:
    ##关闭自我保护机制,保证不可用服务及时剔除
    enable-self-preservation: false
    ##5秒内未收到心跳则剔除
    eviction-interval-timer-in-ms: 5000