server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.169.1.82:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"