server:
  port: 8080

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://192.169.1.135:7001/eureka,http://192.168.1.135:7002/eureka
# 设置feign客户端超时时间(openfeign默认支持ribbon)
ribbon:
  # 从服务端读取的超时时间
  ReadTimeout: 5000
  # 建立连接的超时时间
  ConnectTimeout: 5000

logging:
  level:
    #feign 以什么级别的日志监控哪个接口
    com.chenly.springcloud.service.PaymentFeignService: debug